---
############################ Config file v1 for the MRC Harwell Registration pipeline##################################
## This file is in YAML format - http://www.yaml.org/                                                                ##
## Use spaces for indentations. Do not use tabs. It helps to edit in an IDE such as PyCharm                          ##
##'true' and 'false' must be quoted within elastix param sections or python interperets them as 'True' and 'False'   ##
#######################################################################################################################

output_dir: out
fixed_volume: target/2608145_deformable_avg_8bit_28um.nrrd
inputvolumes_dir: inputs
fixed_mask: target/fixed_mask_for_reg.nrrd
pad_dims: true
threads: 10
filetype: nrrd
compress_averages: true
output_metadata_file: output_metadata.yaml 

# true for creating an average. false for phenotype detection
generate_new_target_each_stage: true



################################### Global registration parameters, applied to all stages ##############################
global_elastix_params:
    FixedInternalImagePixelType: short
    MovingInternalImagePixelType: short
    FixedImageDimension: 3
    MovingImageDimension: 3
    UseDirectionCosines: 'true'
    FixedImagePyramid: FixedSmoothingImagePyramid
    MovingImagePyramid: MovingSmoothingImagePyramid
    ResultImagePixelType: float
    ResultImageFormat: nrrd
    CompressResultImage: 'true'
    Interpolator: BSplineInterpolator
    ResampleInterpolator: FinalBSplineInterpolator
    Resampler: DefaultResampler
    NumberOfHistogramBins: 32
    HowToCombineTransforms: Compose
    NewSamplesEveryIteration: 'true'
    ImageSampler: Random
    FinalBSplineInterpolationOrder: 3
    DefaultPixelValue: 0
    WriteTransformParametersEachIteration: 'false'
    WriteResultImage: 'true'
    AutomaticScalesEstimation: 'true'
    AutomaticTransformInitialization: 'true'

################################ Stage-specific registration parameters ################################################
registration_stage_params:

#### Rigid #############################################################################################################
    
    - stage_id: rigid
      elastix_parameters:
        Metric: AdvancedNormalizedCorrelation
        Registration: MultiResolutionRegistration
        MaximumNumberOfIterations: 400
        NumberOfResolutions: 4
        NumberOfSpatialSamples: 20000
        FixedKernelBSplineOrder: 1
        MovingKernelBSplineOrder: 3
        Transform: EulerTransform
        Optimizer: StandardGradientDescent
        Metric: AdvancedNormalizedCorrelation
        SP_a: [1000.0, 1000.0, 500.0, 500.0]
        SP_alpha: 0.602
        SP_A: 50.0
        FixedLimitRangeRatio: 0.0
        MovingLimitRangeRatio: 0.0
        FixedKernelBSplineOrder: 1
        MovingKernelBSplineOrder: 3
        UseDifferentiableOverlap: 'false'
        



 #### Affine #############################################################################################################

    - stage_id: affine
      elastix_parameters:
        Registration: MultiResolutionRegistration
        NumberOfResolutions: 4
        Optimizer: AdaptiveStochasticGradientDescent
        Transform: AffineTransform
        Metric: AdvancedNormalizedCorrelation
        MaximumNumberOfIterations: 500
        NumberOfSpatialSamples: 10000


#### Deformable registrations. Generate deformation fields etc #################################
    
    - stage_id: deformable_to_128
      elastix_parameters:
        Registration: MultiResolutionRegistration
        NumberOfResolutions: 2
        NumberOfSpatialSamples: 100000
        NumberOfGradientMeasurements: 10
        NumberOfSamplesForExactGradient: 20000
        NumberOfJacobianMeasurements: 4000
        MaximumNumberOfIterations: 250
        AutomaticParameterEstimation: 'true'
        UseAdaptiveStepSizes: 'true'
        ASGDParameterEstimationMethod: DisplacementDistribution
        Optimizer: AdaptiveStochasticGradientDescent
        Transform: BSplineTransform
        Metric: AdvancedMattesMutualInformation
        FinalGridSpacingInVoxels: 128
        MaximumStepLength: 3.0

#### Deformable registrations. Generate deformation fields etc #################################
    
    - stage_id: deformable_to_8
      inherit_elx_params: deformable_to_128
      elastix_parameters:
        NumberOfResolutions: 4
        Registration: MultiMetricMultiResolutionRegistration
        Metric: [AdvancedMattesMutualInformation, TransformRigidityPenalty]
        RigidityPenaltyWeight: [0.0, 0.0, 0.1, 0.1]
        MaximumStepLength: [2.0, 2.0, 1.0, 1.0]
        FinalGridSpacingInVoxels: 8



            
        
            
