---
############################ Config file v1 for the MRC Harwell Registration pipeline##################################
## This file is in YAML format - http://www.yaml.org/                                                                ##
## Use spaces for indentations. Do not use tabs. It helps to edit in an IDE such as PyCharm                          ##
##'true' and 'false' must be quoted within elastix param sections or python interperets them as 'True' and 'False'   ##
#######################################################################################################################


# This is an exmaple config file for creating WT data for running mutants against

pad_dims: [450, 560, 930]

threads: 30
filetype: nrrd

compress_averages: true
fixed_mask: target/mask.nrrd
fixed_volume: target/population_average.nrrd
voxel_size: 14.0
label_map_path: target/labels.nrrd
organ_names: organ_names.txt

# true for creating an average. false for phenotype detection
generate_new_target_each_stage: false

skip_transform_inversion: true

normalisation_roi: [[570, 190, 160], [580, 200, 170]]

generate_deformation_fields: 
    256_to_8: [deformable_256_to_8]
    64_to_8: [deformable_256_to_8, 3, 4, 5, 6]
    32_to_8: [deformable_256_to_8, 4, 5, 6]
    256_to_64: [deformable_256_to_8, 1, 2, 3]

################################### Global registration parameters, applied to all stages ##############################
global_elastix_params:
    FixedInternalImagePixelType: float
    MovingInternalImagePixelType: float
    FixedImageDimension: 3
    MovingImageDimension: 3
    UseDirectionCosines: 'true'
    FixedImagePyramid: FixedShrinkingImagePyramid
    MovingImagePyramid: MovingShrinkingImagePyramid
    ResultImagePixelType: float
    ResultImageFormat: nrrd
    CompressResultImage: 'true'
    Interpolator: BSplineInterpolator
    ResampleInterpolator: FinalBSplineInterpolator
    Resampler: DefaultResampler
    NumberOfHistogramBins: 32
    HowToCombineTransforms: Compose
    NewSamplesEveryIteration: 'true'
    ImageSampler: RandomCoordinate
    FinalBSplineInterpolationOrder: 3
    BSplineInterpolationOrder: 3
    DefaultPixelValue: 0
    WriteTransformParametersEachIteration: 'false'
    WriteTransformParametersEachResolution: 'true'
    WriteResultImage: 'true'
    AutomaticScalesEstimation: 'true'
    AutomaticTransformInitialization: 'true'
    Optimizer: AdaptiveStochasticGradientDescent
    UseRandomSampleRegion: "false"
    
################################ Stage-specific registration parameters ################################################
registration_stage_params:

#### Rigid #############################################################################################################
    
    - stage_id: rigid
      elastix_parameters:
        Metric: AdvancedNormalizedCorrelation
        Registration: MultiResolutionRegistration
        MaximumNumberOfIterations: 400
        NumberOfResolutions: 4
        NumberOfSpatialSamples: 20000
        Transform: EulerTransform
        SP_a: [1000.0, 1000.0, 500.0, 500.0]
        SP_alpha: 0.602
        SP_A: 50.0
        FixedLimitRangeRatio: 0.0
        MovingLimitRangeRatio: 0.0
        FixedKernelBSplineOrder: 1
        MovingKernelBSplineOrder: 3
        UseDifferentiableOverlap: 'false'
        



  #### Affine #############################################################################################################

    - stage_id: affine
      elastix_parameters:
        Registration: MultiResolutionRegistration
        NumberOfResolutions: 4
        Transform: AffineTransform
        Metric: AdvancedNormalizedCorrelation
        MaximumNumberOfIterations: 500
        NumberOfSpatialSamples: 20000



#### Deformable registrations. Regenerate reference from the average of previous stage #################################
    
    - stage_id: deformable_256_to_8
      elastix_parameters:
        Registration: MultiMetricMultiResolutionRegistration
        NumberOfResolutions: 6
        NumberOfSpatialSamples: 40000
        MaximumNumberOfIterations: 800
        AutomaticParameterEstimation: 'true'
        UseAdaptiveStepSizes: 'true'
        Transform: BSplineTransform
        Metric: [AdvancedMattesMutualInformation, TransformBendingEnergyPenalty]
        FinalGridSpacingInVoxels: 8
        GridSpacingSchedule: [32.0, 32.0, 32.0, 16.0, 16.0, 16.0, 8.0, 8.0, 8.0, 4.0, 4.0, 4.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0]
        MaximumStepLength: [3.0, 3.0, 3.0, 2.0, 1.0, 1.0]
        Metric0Weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        Metric1Weight: [0.0, 0.0, 0.0, 0.0, 50.0, 50.0]
        ImagePyramidSchedule: [5, 5, 5, 3, 3, 3, 3, 3, 3, 2, 2, 2, 1, 1, 1, 1, 1, 1]
      
