---
############################ Config file v1 for the MRC Harwell Registration pipeline##################################
## This file is in YAML format - http://www.yaml.org/                                                                ##
## Use spaces for indentations. Do not use tabs. It helps to edit in an IDE such as PyCharm                          ##
##'true' and 'false' must be quoted within elastix param sections or python interperets them as 'True' and 'False'   ##
#######################################################################################################################

# The Fixed volume
fixed_volume: target/301015_deformable_to_8_rescaled_8bit.nrrd
fixed_mask: target/mask_cleaned.nrrd
label_map_path: target/seg_cleaned.nrrd
organ_names: organ_names.txt

# If inverting transforms not required, set to 'true'
#skip_transform_inversion: true

# Pad the volumes to the size of the largest. Options (true/dimensions to pad to in x, y, z - eg [300,256,240])
pad_dims: [210, 275, 404]

# Number of cpu cores to use
threads: 20

# The voxel size of the input images
voxel_size: 28

# true for creating an average. false for phenotype detection Options (true/false)
generate_new_target_each_stage: false

# normalise final output to a region of background noise [z,y,x], [z, y, x]
background_roi_zyx_norm: [[35, 200, 130], [45, 210, 140]]

generate_deformation_fields: deformable_to_64

#restart_at_stage: deformable_to_8


################################### Global registration parameters, applied to all stages ##############################
global_elastix_params:
    FixedInternalImagePixelType: short
    MovingInternalImagePixelType: short
    FixedImageDimension: 3
    MovingImageDimension: 3
    UseDirectionCosines: 'true'
    FixedImagePyramid: FixedSmoothingImagePyramid
    MovingImagePyramid: MovingSmoothingImagePyramid
    ResultImagePixelType: float
    ResultImageFormat: nrrd
    CompressResultImage: 'true'
    Interpolator: BSplineInterpolator
    ResampleInterpolator: FinalBSplineInterpolator
    Resampler: DefaultResampler
    NumberOfHistogramBins: 32
    HowToCombineTransforms: Compose
    NewSamplesEveryIteration: 'true'
    ImageSampler: RandomCoordinate
    FinalBSplineInterpolationOrder: 3
    DefaultPixelValue: 0
    WriteTransformParametersEachIteration: 'false'
    WriteResultImage: 'true'
    AutomaticScalesEstimation: 'true'
    AutomaticTransformInitialization: 'true'

################################ Stage-specific registration parameters ################################################
registration_stage_params:

#### Rigid #############################################################################################################
    
    - stage_id: rigid
      elastix_parameters:
        Metric: AdvancedNormalizedCorrelation
        Registration: MultiResolutionRegistration
        MaximumNumberOfIterations: 600
        NumberOfResolutions: 1
        NumberOfSpatialSamples: 20000
        FixedKernelBSplineOrder: 1
        MovingKernelBSplineOrder: 3
        Transform: EulerTransform
        Optimizer: AdaptiveStochasticGradientDescent
        Metric: AdvancedNormalizedCorrelation
        SP_a: [1000.0, 1000.0, 500.0, 500.0]
        SP_alpha: 0.602
        SP_A: 50.0
        FixedLimitRangeRatio: 0.0
        MovingLimitRangeRatio: 0.0
        FixedKernelBSplineOrder: 1
        MovingKernelBSplineOrder: 3
        UseDifferentiableOverlap: 'false'
        



 #### Affine #############################################################################################################

    - stage_id: affine
      elastix_parameters:
        MaximumNumberOfIterations: 600
        Registration: MultiResolutionRegistration
        NumberOfResolutions: 1
        Optimizer: AdaptiveStochasticGradientDescent
        Transform: AffineTransform
        Metric: AdvancedNormalizedCorrelation
        NumberOfSpatialSamples: 20000


#### Deformable registrations. Generate deformation fields etc #################################
    
    - stage_id: deformable_to_128
      elastix_parameters:
        Registration: MultiResolutionRegistration
        NumberOfResolutions: 1
        NumberOfSpatialSamples: 20000
        NumberOfGradientMeasurements: 10
        NumberOfSamplesForExactGradient: 20000
        NumberOfJacobianMeasurements: 4000
        MaximumNumberOfIterations: 150
        AutomaticParameterEstimation: 'true'
        UseAdaptiveStepSizes: 'true'
        ASGDParameterEstimationMethod: DisplacementDistribution
        Optimizer: AdaptiveStochasticGradientDescent
        Transform: BSplineTransform
        Metric: AdvancedMattesMutualInformation
        FinalGridSpacingInVoxels: 128
        MaximumStepLength: 2.0

    - stage_id: deformable_to_64
      inherit_elx_params: deformable_to_128
      elastix_parameters:
        MaximumNumberOfIterations: 150
        FinalGridSpacingInVoxels: 64
        MaximumStepLength: 2.0

    - stage_id: deformable_to_32
      inherit_elx_params: deformable_to_64
      elastix_parameters:
        MaximumNumberOfIterations: 150
        FinalGridSpacingInVoxels: 32
        MaximumStepLength: 2.0

    - stage_id: deformable_to_16
      inherit_elx_params: deformable_to_32
      elastix_parameters:
        Registration: MultiMetricMultiResolutionRegistration
        Metric: [AdvancedMattesMutualInformation, TransformRigidityPenalty]
        NumberOfResolutions: 1
        FinalGridSpacingInVoxels: 16
        MaximumStepLength: 1.0
        RigidityPenaltyWeight: 0.1

    - stage_id: deformable_to_8
      inherit_elx_params: deformable_to_16
      elastix_parameters:
        FinalGridSpacingInVoxels: 8
        MaximumStepLength: 1.0
        RigidityPenaltyWeight: 0.1
    
    


